#   __ _______    __    ___________________    _______
#  / / \   _  \   \ \   \_   _____/\_____  \   \      \
# / /  /  /_\  \   \ \   |    __)_  /   |   \  /   |   \
# \ \  \  \_/   \  / /   |        \/    |    \/    |    \
#  \_\  \_____  / /_/   /_______  /\_______  /\____|__  /
#             \/                \/         \/         \/
# EYE OF NEMESIS - Example config file.
# Documentation in our wiki: https://github.com/adrianvic/NemesisEye

Policies:
  - name: "Block-illegal-items" # NO SPACES
    type: global
    effect: DENY
    weight: 0
    policyAllowList: false
    nodes:
      - [BREAK, PLACE, HIT, INTERACT]:
          value:
            - BEDROCK
  - name: "Bedrock-allow-admins"
    type: "permission"
    effect: ALLOW
    weight: 1
    permissions:
      - "server.usebedrock"
    nodes:
      - [BREAK, PLACE, HIT, INTERACT]:
          values:
            - BEDROCK