Policies:
  - name: "Bedrock-only-admins"
    type: "permission"
    effect: ALLOW
    weight: 1
    policyAllowList: true
    permissions:
      - "server.usebedrock"
    nodes:
      - [INTERACT]:
          values:
            - BEDROCK

  - name: "Beta-1.7.3-items-only" # No spaces here or else commands which need the name as argument will not work
    type: "location" # global | location | permission | playerName
    effect: ALLOWONLY # DENY | ALLOW (overrides deny) | ALLOWONLY (allow only if met)
    weight: 0 # Greater weight overrides lower
    policyAllowList: false # Inverts the policy validation logic, for example a location policy will affect all players NOT inside it's location
    locations:
      - corner1: { x: 2100, y: 256, z: 1400 }
        corner2: { x: 1000, y: -64, z: 2200 }
    nodes:
      - [INTERACT]:
          values:
            - AIR
            - STONE
            - COBBLESTONE
            - "^(OAK|SPRUCE|BIRCH)_(LOG|SAPLING|PLANKS|LEAVES)$"
            - "^(DIAMOND|GOLD|IRON|COAL|LAPIS|REDSTONE)_ORE$"
            - "^(DIAMOND|GOLD|IRON|LAPIS)_BLOCK$"
            - GRAVEL
            - BEDROCK
            - SAND
            - SPONGE
            - WET_SPONGE
            - GLASS
            - LAPIS_LAZULI
            - COBWEB
            - PISTON
            - STICKY_PISTON
            - GRASS
            - DISPENSER
            - NOTE_BLOCK
            - SANDSTONE
            - RED_BED
            - "^(POWERED|DETECTOR)_RAIL$"
            - RAIL
            - SHORT_GRASS
            - "^(WHITE|BLACK|GREEN|YELLOW|PINK|PURPLE|CYAN|BLUE|RED|LIME|BROWN|LIGHT_GRAY|GRAY)_(WOOL|DYE)$"
            - POPPY
            - DANDELION
            - "^(RED|BROWN)_MUSHROOM$"
            - "^(OAK|COBBLESTONE)_SLAB$"
            - BRICK_BLOCK
            - TNT
            - BOOKSHELF
            - OBSIDIAN
            - MOSSY_COBBLESTONE
            - TORCH
            - SPAWNER
            - REDSTONE
            - CHEST
            - CRAFTING_TABLE
            - FARMLAND
            - FURNACE
            - SIGN
            - LADDER
            - "^(COBBLESTONE|OAK)_STAIRS$"
            - LEVER
            - "^(OAK|STONE)_PRESSURE_PLATE$"
            - "^(OAK|IRON)_DOOR$"
            - BLUE_ICE
            - REDSTONE_TORCH
            - STONE_BUTTON
            - SNOW
            - SNOW_BLOCK
            - CLAY
            - SUGAR_CANE
            - JUKEBOX
            - OAK_FENCE
            - PUMPKIN
            - NETHERRACK
            - SOUL_SAND
            - GLOWSTONE
            - JACK_O_LANTERN
            - CAKE
            - REPEATER
            - OAK_TRAPDOOR
            - "^(IRON|STONE|DIAMOND|WOODEN|GOLDEN)_(SHOVEL|AXE|PICKAXE|SWORD|HOE)$"
            - "^(IRON|LEATHER|DIAMOND|GOLDEN)_(HELMET|CHESTPLATE|LEGGINGS|BOOTS)$"
            - STICK
            - BOWL
            - MUSHROOM_STEW
            - FEATHER
            - STRING
            - GUNPOWDER
            - WHEAT_SEEDS
            - WHEAT
            - FLINT
            - FLINT_AND_STEEL
            - PORKCHOP
            - "^(COOKED|RAW)_(PORKCHOP|FISH)$"
            - PAINTING
            - GOLDEN_APPLE
            - BUCKET
            - "^(LAVA|MILK|WATER)_BUCKET$"
            - MINECART
            - SADDLE
            - SNOWBALL
            - OAK_BOAT
            - LEATHER
            - "^(FURNACE|CHEST)_MINECART$"
            - EGG
            - BOOK
            - PAPER
            - BRICK
            - SLIME_BALL
            - COMPASS
            - FISHING_ROD
            - CLOCK
            - GLOWSTONE_DUST
            - INK_SAC
            - BONE_MEAL
            - SUGAR
            - COOKIE
            - MAP
            - FILLED_MAP
            - SHEARS
            - MUSIC_DISK_CAT
            - MUSIC_DISK_13
            - DIRT
            - BREAD
      - [USE_ENCHANTMENT]:
          "flying bananas": "0"