name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        
      - name: Setup Java enviroment
        uses: actions/setup-java@v5.1.0
        with:
          distribution: termurin
          java-version: 21
        
      - name: Setup Gradle
        uses: gradle/actions@v5.0.0
        
      - name: Build with Gradle
        run: ./gradlew buildAll

      - name: Upload artifacts
        uses: actions/upload-artifact@v6.0.0
        with:
          path: build/libs/*.jar
